worker_unavailable(anande,fri,0-0).
worker_unavailable(anande,sat,0-0).
worker_unavailable(anande,sun,0-0).
worker_unavailable(anande,mon,12-16).
worker_unavailable(anande,tue,12-16).
worker_unavailable(anande,wed,12-16).
worker_unavailable(anande,thu,17-23).
worker_unavailable(clementine,fri,3.5-6.5).
worker_unavailable(clementine,sat,4.5-22).
worker_unavailable(clementine,sun,6-6.5).
worker_unavailable(clementine,mon,0-0).
worker_unavailable(clementine,tue,0-0).
worker_unavailable(clementine,wed,0-0).
worker_unavailable(clementine,thu,0-0).
worker_unavailable(erika,fri,3.5-6.5).
worker_unavailable(erika,sat,4.5-22).
worker_unavailable(erika,sun,6-6.5).
worker_unavailable(erika,mon,0-0).
worker_unavailable(erika,tue,0-0).
worker_unavailable(erika,wed,0-0).
worker_unavailable(erika,thu,0-0).
worker_unavailable(bobby,fri,0-0).
worker_unavailable(bobby,sat,0-0).
worker_unavailable(bobby,sun,0-0).
worker_unavailable(bobby,mon,0-0).
worker_unavailable(bobby,tue,0-0).
worker_unavailable(bobby,wed,0-0).
worker_unavailable(bobby,thu,0-0).
worker_unavailable(dan,fri,0-0).
worker_unavailable(dan,sat,0-0).
worker_unavailable(dan,sun,0-0).
worker_unavailable(dan,mon,0-0).
worker_unavailable(dan,tue,0-0).
worker_unavailable(dan,wed,0-0).
worker_unavailable(dan,thu,0-0).
worker_unavailable(koerner,fri,0-0).
worker_unavailable(koerner,sat,0-0).
worker_unavailable(koerner,sun,0-0).
worker_unavailable(koerner,mon,0-0).
worker_unavailable(koerner,tue,0-0).
worker_unavailable(koerner,wed,0-0).
worker_unavailable(koerner,thu,0-0).
worker_unavailable(danny,fri,0-0).
worker_unavailable(danny,sat,0-0).
worker_unavailable(danny,sun,0-0).
worker_unavailable(danny,mon,0-0).
worker_unavailable(danny,tue,0-0).
worker_unavailable(danny,wed,0-0).
worker_unavailable(danny,thu,0-0).
worker_unavailable(shreya,fri,0-0).
worker_unavailable(shreya,sat,0-0).
worker_unavailable(shreya,sun,0-0).
worker_unavailable(shreya,mon,0-0).
worker_unavailable(shreya,tue,0-0).
worker_unavailable(shreya,wed,0-0).
worker_unavailable(shreya,thu,0-0).
worker_unavailable(crista,fri,0-0).
worker_unavailable(crista,sat,0-0).
worker_unavailable(crista,sun,0-0).
worker_unavailable(crista,mon,0-0).
worker_unavailable(crista,tue,0-0).
worker_unavailable(crista,wed,0-0).
worker_unavailable(crista,thu,0-0).
worker_unavailable(elijah,fri,8-14).
worker_unavailable(elijah,sat,0-0).
worker_unavailable(elijah,sun,11.5-23).
worker_unavailable(elijah,mon,0-0).
worker_unavailable(elijah,tue,0-0).
worker_unavailable(elijah,wed,0-0).
worker_unavailable(elijah,thu,0-0).
worker_unavailable(kete,fri,0-0).
worker_unavailable(kete,sat,0-0).
worker_unavailable(kete,sun,0-0).
worker_unavailable(kete,mon,0-0).
worker_unavailable(kete,tue,0-0).
worker_unavailable(kete,wed,0-0).
worker_unavailable(kete,thu,0-0).
worker_unavailable(heike,fri,0-0).
worker_unavailable(heike,sat,7-12).
worker_unavailable(heike,sun,12-23).
worker_unavailable(heike,mon,1-23).
worker_unavailable(heike,tue,1-23).
worker_unavailable(heike,wed,1-12).
worker_unavailable(heike,thu,0-0).
worker_unavailable(elspeth,fri,1-9).
worker_unavailable(elspeth,fri,1-23).
worker_unavailable(elspeth,sat,1-8).
worker_unavailable(elspeth,sat,10-16).
worker_unavailable(elspeth,sat,19-23).
worker_unavailable(elspeth,sun,1-10).
worker_unavailable(elspeth,sun,19-23).
worker_unavailable(elspeth,mon,16-18).
worker_unavailable(elspeth,mon,19-23).
worker_unavailable(elspeth,tue,19-23).
worker_unavailable(elspeth,wed,19-23).
worker_unavailable(elspeth,thu,19-23).
worker_unavailable(tim,fri,1-23).
worker_unavailable(tim,sat,1-23).
worker_unavailable(tim,sun,1-23).
worker_unavailable(tim,mon,1-23).
worker_unavailable(tim,tue,1-18).
worker_unavailable(tim,wed,0-0).
worker_unavailable(tim,thu,19-23).
worker_unavailable(ox,fri,13-16).
worker_unavailable(ox,fri,18-20).
worker_unavailable(ox,sat,9-12).
worker_unavailable(ox,sat,16-18).
worker_unavailable(ox,sun,15-18).
worker_unavailable(ox,mon,13-18).
worker_unavailable(ox,tue,16-18).
worker_unavailable(ox,wed,16-18).
worker_unavailable(ox,wed,19-21).
worker_unavailable(ox,thu,13-16).
worker_unavailable(scott,fri,6-22).
worker_unavailable(scott,sat,6-12).
worker_unavailable(scott,sat,15-22.5).
worker_unavailable(scott,sun,16-22.5).
worker_unavailable(scott,mon,19-22.5).
worker_unavailable(scott,tue,19-22.5).
worker_unavailable(scott,wed,6-22.5).
worker_unavailable(scott,thu,0-0).
worker_unavailable(adder,fri,10-21.5).
worker_unavailable(adder,sat,16-19).
worker_unavailable(adder,sat,12-16).
worker_unavailable(adder,sat,7-10).
worker_unavailable(adder,sun,12.5-16).
worker_unavailable(adder,sun,19-22.5).
worker_unavailable(adder,mon,12-18).
worker_unavailable(adder,tue,19-22.5).
worker_unavailable(adder,tue,9-12).
worker_unavailable(adder,wed,19-22.5).
worker_unavailable(adder,wed,12.5-16).
worker_unavailable(adder,thu,19-22.5).
worker_unavailable(adder,thu,12-16).
worker_unavailable(adder,thu,6-10).
worker_unavailable(arlo,fri,6-12).
worker_unavailable(arlo,sat,0-0).
worker_unavailable(arlo,sun,10-12).
worker_unavailable(arlo,mon,13-18).
worker_unavailable(arlo,tue,0-0).
worker_unavailable(arlo,wed,0-0).
worker_unavailable(arlo,thu,13-22.5).
worker_unavailable(becky,fri,0-0).
worker_unavailable(becky,sat,13-22.5).
worker_unavailable(becky,sun,13-22.5).
worker_unavailable(becky,mon,0-0).
worker_unavailable(becky,tue,0-0).
worker_unavailable(becky,wed,0-0).
worker_unavailable(becky,thu,6-21.5).
worker_unavailable(birddog,fri,7-11).
worker_unavailable(birddog,fri,16-22.5).
worker_unavailable(birddog,sat,8-12).
worker_unavailable(birddog,sat,16-22.5).
worker_unavailable(birddog,sun,6-17).
worker_unavailable(birddog,sun,17-22.5).
worker_unavailable(birddog,mon,8-12).
worker_unavailable(birddog,mon,16-22.5).
worker_unavailable(birddog,tue,8-12).
worker_unavailable(birddog,tue,17-22.5).
worker_unavailable(birddog,wed,8-12).
worker_unavailable(birddog,wed,16-22.5).
worker_unavailable(birddog,thu,8-12).
worker_unavailable(birddog,thu,13-20).
worker_unavailable(brandy,fri,7-12).
worker_unavailable(brandy,sat,7-12).
worker_unavailable(brandy,sun,7-12).
worker_unavailable(brandy,mon,10-12).
worker_unavailable(brandy,mon,13-15).
worker_unavailable(brandy,tue,7-12).
worker_unavailable(brandy,tue,19-22.5).
worker_unavailable(brandy,wed,7-12).
worker_unavailable(brandy,thu,7-12).
worker_unavailable(brandy,thu,13-15).
worker_unavailable(cel,fri,9-12).
worker_unavailable(cel,fri,13-16).
worker_unavailable(cel,sat,9-12).
worker_unavailable(cel,sun,6-22).
worker_unavailable(cel,mon,9-13).
worker_unavailable(cel,tue,9-12).
worker_unavailable(cel,wed,7-12).
worker_unavailable(cel,thu,8.5-12).
worker_unavailable(cel,thu,17-19).
worker_unavailable(christine,fri,6-9).
worker_unavailable(christine,sat,6-22.5).
worker_unavailable(christine,sun,0-0).
worker_unavailable(christine,mon,8-12).
worker_unavailable(christine,tue,0-0).
worker_unavailable(christine,wed,12-18).
worker_unavailable(christine,thu,8-12).
worker_unavailable(christine,thu,13-22.5).
worker_unavailable(brittany,fri,8-14).
worker_unavailable(brittany,sat,10-12).
worker_unavailable(brittany,sat,13.5-16).
worker_unavailable(brittany,sun,18-22).
worker_unavailable(brittany,mon,7-11).
worker_unavailable(brittany,tue,7-11).
worker_unavailable(brittany,tue,16-22.5).
worker_unavailable(brittany,wed,7-11).
worker_unavailable(brittany,wed,19-22).
worker_unavailable(brittany,thu,11.5-21.5).
worker_unavailable(danjo,fri,6-12).
worker_unavailable(danjo,fri,11.5-12).
worker_unavailable(danjo,sat,6-12).
worker_unavailable(danjo,sun,6-12).
worker_unavailable(danjo,mon,6-12).
worker_unavailable(danjo,tue,6-12).
worker_unavailable(danjo,wed,6-12).
worker_unavailable(danjo,thu,6-12).
worker_unavailable(danjo,thu,18-22.5).
worker_unavailable(emily,fri,7-11).
worker_unavailable(emily,sat,7-11).
worker_unavailable(emily,sat,13-16).
worker_unavailable(emily,sun,6-10).
worker_unavailable(emily,sun,16-22).
worker_unavailable(emily,mon,7-11).
worker_unavailable(emily,mon,12-16).
worker_unavailable(emily,mon,19-22.5).
worker_unavailable(emily,tue,7-11).
worker_unavailable(emily,wed,6-21).
worker_unavailable(emily,thu,6-20.5).
worker_unavailable(emily,thu,20.5-22).
worker_unavailable(jeli,fri,6-19).
worker_unavailable(jeli,sat,12-22.5).
worker_unavailable(jeli,sun,0-0).
worker_unavailable(jeli,mon,0-0).
worker_unavailable(jeli,tue,0-0).
worker_unavailable(jeli,wed,0-0).
worker_unavailable(jeli,thu,16-22).
worker_unavailable(kele,fri,6-10).
worker_unavailable(kele,fri,18-22.5).
worker_unavailable(kele,sat,6-22.5).
worker_unavailable(kele,sun,6-22.5).
worker_unavailable(kele,mon,6-10).
worker_unavailable(kele,mon,18-22.5).
worker_unavailable(kele,tue,6-10).
worker_unavailable(kele,tue,18-22.5).
worker_unavailable(kele,tue,12-16).
worker_unavailable(kele,wed,6-10).
worker_unavailable(kele,thu,6-10).
worker_unavailable(kele,thu,12-22.5).
worker_unavailable(lindsey,fri,10-12).
worker_unavailable(lindsey,sat,10-12).
worker_unavailable(lindsey,sat,13-18).
worker_unavailable(lindsey,sun,6-17).
worker_unavailable(lindsey,sun,17-22.5).
worker_unavailable(lindsey,mon,19-22.5).
worker_unavailable(lindsey,tue,19-22.5).
worker_unavailable(lindsey,tue,18-19).
worker_unavailable(lindsey,wed,6-15.5).
worker_unavailable(lindsey,thu,15.5-22.5).
worker_unavailable(nina,fri,8-14).
worker_unavailable(nina,fri,18-22.5).
worker_unavailable(nina,sat,8-18).
worker_unavailable(nina,sun,10-12).
worker_unavailable(nina,sun,19-21.5).
worker_unavailable(nina,mon,19-22.5).
worker_unavailable(nina,mon,8-16).
worker_unavailable(nina,tue,8-22.5).
worker_unavailable(nina,wed,0-0).
worker_unavailable(nina,thu,18-19).
worker_unavailable(pax,fri,6-22.5).
worker_unavailable(pax,sat,0-0).
worker_unavailable(pax,sun,0-0).
worker_unavailable(pax,mon,6-22.5).
worker_unavailable(pax,tue,13-15).
worker_unavailable(pax,tue,19-22.5).
worker_unavailable(pax,wed,0-0).
worker_unavailable(pax,thu,19-22.5).
worker_unavailable(pax,thu,13-15).
worker_unavailable(pax,thu,9-13).
worker_unavailable(puck,fri,7-11).
worker_unavailable(puck,fri,20-22.5).
worker_unavailable(puck,sat,8-12).
worker_unavailable(puck,sat,16-18).
worker_unavailable(puck,sat,19.5-22.5).
worker_unavailable(puck,sun,6-22).
worker_unavailable(puck,mon,7-11).
worker_unavailable(puck,tue,7-11).
worker_unavailable(puck,tue,16-18).
worker_unavailable(puck,tue,20-22.5).
worker_unavailable(puck,wed,7-18.5).
worker_unavailable(puck,wed,18.5-22.5).
worker_unavailable(puck,thu,6-11).
worker_unavailable(puck,thu,16-22.5).
worker_unavailable(reynaldo,fri,0-0).
worker_unavailable(reynaldo,sat,0-0).
worker_unavailable(reynaldo,sun,0-0).
worker_unavailable(reynaldo,mon,6-19).
worker_unavailable(reynaldo,tue,19-22.5).
worker_unavailable(reynaldo,wed,6-22).
worker_unavailable(reynaldo,thu,6-7).
worker_unavailable(rosie,fri,7-11).
worker_unavailable(rosie,sat,7-11).
worker_unavailable(rosie,sat,12-13).
worker_unavailable(rosie,sun,10.5-21.5).
worker_unavailable(rosie,mon,6.5-21.5).
worker_unavailable(rosie,tue,6-22).
worker_unavailable(rosie,wed,6-17).
worker_unavailable(rosie,wed,17-22).
worker_unavailable(rosie,thu,6-22).
worker_unavailable(rowan,fri,6-17).
worker_unavailable(rowan,fri,17-22.5).
worker_unavailable(rowan,sat,6-22.5).
worker_unavailable(rowan,sun,11-22).
worker_unavailable(rowan,mon,6-18).
worker_unavailable(rowan,tue,10-12).
worker_unavailable(rowan,wed,12-18).
worker_unavailable(rowan,thu,13-15).
worker_unavailable(rowan,thu,17-18).
worker_unavailable(sky,fri,6-9).
worker_unavailable(sky,sat,6-12).
worker_unavailable(sky,sat,16-22.5).
worker_unavailable(sky,sun,6-10).
worker_unavailable(sky,mon,6-9).
worker_unavailable(sky,mon,13-15).
worker_unavailable(sky,tue,6-9).
worker_unavailable(sky,tue,19-22.5).
worker_unavailable(sky,wed,6-9).
worker_unavailable(sky,thu,6-9).
worker_unavailable(sky,thu,13-15).
worker_unavailable(tigger,fri,6-21.5).
worker_unavailable(tigger,sat,6-21).
worker_unavailable(tigger,sun,6-12).
worker_unavailable(tigger,mon,6-9).
worker_unavailable(tigger,tue,6-9).
worker_unavailable(tigger,wed,6-9).
worker_unavailable(tigger,thu,6-9).
worker_unavailable(tigger,thu,13-21).
worker_unavailable(trout,fri,6-7).
worker_unavailable(trout,fri,10-18).
worker_unavailable(trout,fri,20-22.5).
worker_unavailable(trout,sat,6-7).
worker_unavailable(trout,sat,10-18).
worker_unavailable(trout,sat,20-22.5).
worker_unavailable(trout,sun,6-7).
worker_unavailable(trout,sun,8-18).
worker_unavailable(trout,sun,20-22.5).
worker_unavailable(trout,mon,6-7).
worker_unavailable(trout,mon,13-18).
worker_unavailable(trout,mon,20-22.5).
worker_unavailable(trout,tue,6-7).
worker_unavailable(trout,tue,13-18).
worker_unavailable(trout,tue,20-22.5).
worker_unavailable(trout,wed,6-7).
worker_unavailable(trout,wed,13-18).
worker_unavailable(trout,wed,20-22.5).
worker_unavailable(trout,thu,6-7).
worker_unavailable(trout,thu,12-18).
worker_unavailable(trout,thu,20-22.5).
worker_unavailable(fox,fri,6-11).
worker_unavailable(fox,fri,15-16).
worker_unavailable(fox,fri,18-22.5).
worker_unavailable(fox,sat,6-22.5).
worker_unavailable(fox,sun,6-12).
worker_unavailable(fox,sun,18-22.5).
worker_unavailable(fox,mon,6-12).
worker_unavailable(fox,mon,18-22.5).
worker_unavailable(fox,tue,6-12).
worker_unavailable(fox,tue,18-22.5).
worker_unavailable(fox,wed,6-11).
worker_unavailable(fox,wed,18-22.5).
worker_unavailable(fox,thu,6-15).
worker_unavailable(fox,thu,18-22.5).
