workers={
"adder": "[ket1, ket2, ketcleanhonch, ketcleanhelp, curd1, curd2, trays1, trays2, trays3]",
"anande": "[packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]",
"arlo": "[ket1,ket2,ketcleanhonch,ketcleanhelp]",
"becky": "[curd1,curd2]",
"birddog": "[packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2, trayscleanhelp, ketcleanhelp]",
"brandy": "[trays1,trays2,trays3,trayscleanhonch]",
"brittany": "[packhonch1,packhonch2,packhonch3,packhonch4,packhelp1,packhelp2,packhelp3,packhelp4,packhelp2_1,packhelp2_2,trays1,trays2,trays3]",
"christian": "[trays1,trays2,trays3,trayscleanhonch,trayscleanhelp]",
"cj": "[packhonch1, packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2, trayscleanhonch, trayscleanhelp]",
"claire": "[packhonch1, packhonch2, packhonch3, packhonch4, packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]",
"danjo": "[ketcleanhonch,ketcleanhelp]",
"elijah": "[curd1, curd2, prep, meta]",
"emily": "[trays1,trays2,trays3]",
"ezra": "[trays1, trays2, trays3]",
"fox": "[packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]",
"jeli": "[packhonch1, packhonch2, packhonch3, packhonch4]",
"jen": "[packhonch1, packhelp1, packhelp2_1]",
"kami": "[trays1,trays2,trays3, ket1, ket2, startup]",
"kete": "[ket1, ket2, curd1, curd2]",
"mala": "[packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2, trayscleanhelp, trayscleanhonch]",
"pax": "[trays1, trays2, trays3, curd1, curd2]",
"puck": "[ket1,ket2, curd1, curd2, trays1, trays2, trays3, trayscleanhelp, trayscleanhonch]",
"rowan": "[packhonch1, packhonch2, packhonch3, packhonch4, packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]",
"sansann": "[packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2, trayscleanhelp, ketcleanhelp, ketcleanhonch]",
"scott": "[packhonch1, packhonch2, packhonch3, packhonch4, packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2, trays1, trays2, trays3]",
"tim": "[curd1, curd2]",
"cell": "[packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2, trayscleanhonch,trayscleanhelp]",
"daniel": "[any]",
"gordon": "[ketcleanhelp]",
"kera": "[curd1, curd2,packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]",
"lindsey": "[trayscleanhelp]",
"madge": "[packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]",
"nina": "[trays1,trays2,trays3]",
"paul": "[ket1,ket2]",
"reynaldo": "[trays1,trays2,trays3]",
"rosie": "[packhonch1, packhonch2, packhonch3, packhonch4]",
"sky": "[ket1,ket2,ketcleanhonch,curd1,curd2]",
"stephan": "[packhonch1, packhonch2, packhonch3, packhonch4, packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]",
"tigger": "[trays1,trays2,trays3]",
"johnny": "[ket1,ket2]",
"allpack": "[packhonch1, packhonch2, packhonch3, packhonch4, packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]",
"allpackhelp": "[packhelp1, packhelp2, packhelp3, packhelp4, packhelp2_1, packhelp2_2]"}
